logging_level: INFO

scenario-totals:
  clusters: [100]
  opts: [2H]

alternative-totals:
  epsilon: [0.005, 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1]
  category: ['totals']

scenario-groups:
  clusters: [100]
  opts: [2H]

alternative-groups:
  epsilon: [0.05]
  category: ['groups']

solving:
  options:
    formulation: kirchhoff
    skip_iterations: true
    clip_p_max_pu: 0.01
  solver:
    name: gurobi
    threads: 4
    method: 2 # barrier
    crossover: 0
    BarConvTol: 1.e-3
    FeasibilityTol: 1.e-3
    AggFill: 0
    PreDual: 0
    GURO_PAR_BARDENSETHRESH: 200
    BarHomogeneous: 1

lines_and_links_separate: false
include_groups: false
include_hypercube: false
include_non_extendable: true
excluded_carriers: [OCGT, CCGT, offwind-ac, offwind-dc]

lines:
  s_max_pu: 0.7
  s_nom_add: 8000
  s_nom_factor: 2

links:
  p_nom_max: 20000

plotting:
  tech_colors:
    wind: "#072e6e"
    onwind: "#235ebc"
    offwind: "#6895dd"
    offwind-ac: "#6895dd"
    offwind-dc: "#74c6f2"
    hydro: "#246e64"
    PHS: "#08ad97"
    ror: "#4adbc8"
    solar: "#f9d002"
    battery: "#b8ea04"
    H2: "#ea048a"
    AC: "#70af1d"
    DC: "#8a1caf"
    all-Transmission: "#70af1d"
    all-StorageUnit: "#ff9000"
    none: "#dddddd"
  nice_names:
    wind: "Wind"
    onwind: "Onshore Wind"
    offwind: "Offshore Wind"
    offwind-ac: "Offshore Wind (AC)"
    offwind-dc: "Offshore Wind (DC)"
    hydro: "Hydro Reservoirs"
    PHS: "Pumped Hydro"
    ror: "Run of River"
    solar: "Solar PV"
    battery: "Battery"
    H2: "Hydrogen"
    AC: "HVAC Lines"
    DC: "HVDC Links"
    all-Transmission: "Transmission"
    all-StorageUnit: "Storage"
    none: "No Dominant Carrier"
