logging_level: INFO

scenario:
  clusters: [30]
  ll: ['vopt']
  snapshots: [100]
  opts: [Co2L0.05-1H, Co2L0.2-1H]

alternative:
  epsilon: [0.01, 0.05]
  category: ['hypercube', 'groups']

solving:
  options:
    formulation: kirchhoff
    min_iterations: 0
    max_iterations: 1
    clip_p_max_pu: 0.01
  solver:
    name: gurobi
    threads: 4
    method: 2 # barrier
    crossover: 0
    BarConvTol: 1.e-5
    FeasibilityTol: 1.e-6
    AggFill: 0
    PreDual: 0
    GURO_PAR_BARDENSETHRESH: 200