logging_level: INFO

scenario-totals:
  clusters: [100]
  opts: [2H]

alternative-totals:
  epsilon: [0.005, 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1]
  category: ['totals']

scenario-groups:
  clusters: [100]
  opts: [2H]

alternative-groups:
  epsilon: [0.05]
  category: ['groups']

solving:
  options:
    formulation: kirchhoff
    skip_iterations: true
    clip_p_max_pu: 0.01
  solver:
    name: gurobi
    threads: 4
    method: 2 # barrier
    crossover: 0
    BarConvTol: 1.e-4
    FeasibilityTol: 1.e-5
    AggFill: 0
    PreDual: 0
    GURO_PAR_BARDENSETHRESH: 200
    BarHomogeneous: 1

lines_and_links_separate: false
include_groups: false
include_hypercube: false
include_non_extendable: true
excluded_carriers: [OCGT, CCGT, offwind-ac, offwind-dc]

lines:
  s_max_pu: 0.7
  s_nom_add: 8000
  s_nom_factor: 2

links:
  p_nom_max: 20000