logging_level: INFO

scenario-totals:
  clusters: [100]
  ll: ['copt']
  snapshots: [8760]
  opts: [Co2L0.0-2H, Co2L0.05-2H, Co2L0.2-2H]

alternative-totals:
  epsilon: [0.005, 0.01, 0.02, 0.03, 0.04, 0.05, 0.075, 0.1]
  category: ['totals']

scenario-groups:
  clusters: [100]
  ll: ['copt']
  snapshots: [8760]
  opts: [Co2L0.0-2H]

alternative-groups:
  epsilon: [0.05]
  category: ['groups']

solving:
  options:
    formulation: kirchhoff
    min_iterations: 0
    max_iterations: 1
    clip_p_max_pu: 0.01
  solver:
    name: gurobi
    threads: 4
    method: 2 # barrier
    crossover: 0
    BarConvTol: 1.e-5
    FeasibilityTol: 1.e-6
    AggFill: 0
    PreDual: 0
    GURO_PAR_BARDENSETHRESH: 200

lines_and_links_separate: false
include_groups: false
include_hypercube: false
line_additional_circuits: 4
link_p_nom_max: 30000
excluded_carriers: [OCGT, CCGT, offwind-ac, offwind-dc]