name: pypsa-eur-mga
channels:
  - conda-forge
  - bioconda
dependencies:
  - python
  - pip

  #- pypsa>=0.14  # until pypsa/pypsa#102 closed
  - atlite

  # Dependencies of the workflow itself
  - xlrd
  - scikit-learn
  - pycountry
  - seaborn
  - snakemake-minimal
  - memory_profiler
  - yaml
  - pytables

  # Second order dependencies which should really be deps of atlite
  - xarray
  - netcdf4
  - bottleneck
  - toolz
  - dask
  - progressbar2

  # Include ipython so that one does not inadvertently drop out of the conda
  # environment by calling ipython
  - ipython

  # GIS dependencies have to come all from conda-forge
  - conda-forge::cartopy
  - conda-forge::fiona
  - conda-forge::pyproj<=1.9.6 # until cartopy release with proj>=6.2
  - conda-forge::pyshp
  - conda-forge::geopandas
  - conda-forge::rasterio
  - conda-forge::shapely
  - conda-forge::libgdal

  - pip:
    - vresutils>=0.3
    - git+https://github.com/PyPSA/pypsa.git#egg=pypsa  # until pypsa/pypsa#102 closed
    - git+https://github.com/PyPSA/glaes.git#egg=glaes
    - git+https://github.com/PyPSA/geokit.git#egg=geokit
    - cdsapi
    - powerplantmatching
    - tsam
